enum tokentypes { TEOF, 
	TERROR, TCOMMENT, TNUMBER, TIDENT, 
	TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, 
	TADD, TSUB, TMUL, TDIV, TMOD,
	TASSIGN, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN,
	TNOT, TAND, TOR,
	TEQUAL, TNOTEQU, TLESS, TLESSE, TGREAT, TGREATE,  
	TINC, TDEC, 
	TLPAREN, TRPAREN, TCOMMA, TLBRACE, TRBRACE, TLBRACKET, TRBRACKET, TSEMI
};
